---
- name: Deploy apk-server
  hosts: all
  become: no
  become_user: dfadmin
  gather_facts: False
  tasks:
  - name: Deploy Terraform Instance site03_DB 
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/darwin_cluster-03-04/site03_db/
    ignore_errors: yes

  - name: Deploy Terraform Instance site03_app1
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/darwin_cluster-03-04/site03_1/
    ignore_errors: yes

  - name: Deploy Terraform Instance site03_app2
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/darwin_cluster-03-04/site03_2/
    ignore_errors: yes

  - name: Deploy Terraform Instance site03_app3
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/darwin_cluster-03-04/site03_3/
    ignore_errors: yes

  - name: Deploy Terraform Instance site03_app4
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/darwin_cluster-03-04/site03_4/
    ignore_errors: yes

  - name: Deploy Terraform Instance site04_DB
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/darwin_cluster-03-04/site04_db
    ignore_errors: yes

  - name: Deploy Terraform Instance site04_app1
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/darwin_cluster-03-04/site04_1/
    ignore_errors: yes

  - name: Deploy Terraform Instance site04_app2
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/darwin_cluster-03-04/site04_2/
    ignore_errors: yes

#  - name: Deploy Terraform Instance site04_app3
#    command: terraform apply --auto-approve
#    args:
#       chdir: /home/dfadmin/darwin_cluster-03-04/site04_3/
#    ignore_errors: yes

#  - name: Deploy Terraform Instance site04_app4
#    command: terraform apply --auto-approve
#    args:
#       chdir: /home/dfadmin/darwin_cluster-03-04/site04_4/
#    ignore_errors: yes

  - name: Deploy Terraform Instance tiebreaker34
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/darwin_cluster-03-04/tiebreaker34/
    ignore_errors: yes
