---
- name: Deploy apk-server
  hosts: all
  become: yes
  gather_facts: False
  tasks:
  - name: Deploy Terraform Instance
       shell: '/home/dfadmin/terraform_dev_migration/terraform_APK/terraform apply --auto-approve'
    ignore_errors: yes
