---
- name: Deploy apk-server
  hosts: all
  become: no
  become_user: dfadmin
  gather_facts: False
  tasks:
  - name: Deploy Terraform Instance site07_DB 
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site07_db/
    ignore_errors: yes

  - name: Deploy Terraform Instance site07_app1
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site07_1/
    ignore_errors: yes

  - name: Deploy Terraform Instance site07_app2
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site07_2/
    ignore_errors: yes

  - name: Deploy Terraform Instance site07_app3
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site07_3/
    ignore_errors: yes

  - name: Deploy Terraform Instance site07_app4
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site07_4/
    ignore_errors: yes

  - name: Deploy Terraform Instance site07_app5
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site07_5/
    ignore_errors: yes

  - name: Deploy Terraform Instance site06_DB
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site06_db/
    ignore_errors: yes

  - name: Deploy Terraform Instance site06_app1
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site06_1/
    ignore_errors: yes

  - name: Deploy Terraform Instance site06_app2
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site06_2/
    ignore_errors: yes

  - name: Deploy Terraform Instance site06_app3
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site06_3/
    ignore_errors: yes

  - name: Deploy Terraform Instance site06_app4
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site06_4/
    ignore_errors: yes

  - name: Deploy Terraform Instance site06_app5
    command: terraform apply --auto-approve
    args:
       chdir: /home/dfadmin/cluster-06-07_copernicus/terraform_site06_5/
    ignore_errors: yes
