---
- name: Deploy apk-server
  hosts: all
  become: no
  become_user: dfadmin
  gather_facts: False
  tasks:
  - name: Deploy Terraform Instance
    command: /home/dfadmin/terraform_dev_migration/terraform_APK/terraform apply --auto-approve
    ignore_errors: yes
