---
- name: Deploy apk-server
  hosts: all
  become: no
  become_user: dfadmin
  gather_facts: False
  tasks:
  - name: Deploy Terraform Instance
    command: terraform apply --auto-approve
        args:
          chdir: /home/dfadmin/terraform_dev_migration/terraform_APK/
    ignore_errors: yes
